#!/usr/bin/python

import os, sys, time, subprocess

if __name__=='__main__':
    """
    if len(sys.argv)<2:
        filename = '/home/chrono/neuro/data/hasenstaub/256chan/snapshot_20151123-212835.h5'
        dataset = WillowDataset(filename, -1)
    else:
        filename = sys.argv[1]
        dataset = WillowDataset(filename, -1)
    dataset.importData()
    """

    p1 = subprocess.Popen(['./shank1'])
    #p2 = subprocess.Popen(['./shank2'])

    # wait for child processes to finish
    p1.wait()
