#!/usr/bin/python -i

import numpy as np
import sys, h5py

import matplotlib.pyplot as plt

if __name__ == '__main__':
    if len(sys.argv)<2:
        print 'Usage:'
        print ' $ ./plotGPIO.py <filename.h5>'
        sys.exit()
    filename = sys.argv[1]
    fileObject = h5py.File(filename)
    sidx = np.array(fileObject['sample_index'])
    nsamples = len(sidx)
    aux = np.array(fileObject['aux_data']).reshape(nsamples, 96).transpose()
    # only a subset of the samples contain GPIO (2khz)
    GPIObitfield = aux[0, :] # any i s.t. (i%3==0) would work here
    # now deconstruct the bitfield into separate channels
    GPIO = np.zeros((16,len(GPIObitfield)))
    x = np.arange(len(GPIObitfield))
    for i in range(16):
        GPIO[i,:] = np.bool_(GPIObitfield & (1 << i))
    for i in range(16):
        plt.step(x, GPIO[i,:] + 2*i + 1)
    plt.ylim([0,33])
    plt.show()
