#!/usr/bin/env python2

import sys, subprocess

if __name__=='__main__':
    if len(sys.argv)<2:
        print 'Usage: ./main <snapshot_filename.h5>'
        sys.exit(1)
    else:
        filename = sys.argv[1]

    subproc = subprocess.Popen(['../lib/py/ShankPlot.py', filename,
                                'probeMap_256_P4_level2_canonical.p', '0'])
    subproc.wait()
